select
	CODE_NOM_COD as TYPE_CODE,
	CODE_VAL_COD as CODE,
	CODE_DES as CODE_DESC,
	CODE_DD_DES_COD as DATE_DEBUT,
	CODE_DF_DES_COD as DATE_FIN
from PROD.V_DES_COD
order by TYPE_CODE, CODE, DATE_DEBUT;
