select
	f.NMED_COD_FORME_MED as COD_FORME,
	f.NMED_NOM_FORME as NOM_FORME,
	f.NMED_NOM_FORME_ABR as NOM_FORME_ABR,
	f.NMED_NOM_ANGL_FORME as NOM_ANGL_FORME,
	f.NMED_COD_TYP_FORME as COD_TYP_FORME,
	d.CODE_DES as NOM_TYPE_FORME
from PROD.V_FORME_MED as f
left join PROD.V_DES_COD as d on d.CODE_VAL_COD = f.NMED_COD_TYP_FORME
							  and d.code_nom_cod = 'COD_TYP_FORME'
order by COD_FORME;
